package cl.mapuescuela.pedidos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PedidoDAO {

    private final Connection conn;

    public PedidoDAO(Connection conn) {
        this.conn = conn;
    }

    public void crearTablas() throws SQLException {
        try (Statement st = conn.createStatement()) {

            st.execute("""
                CREATE TABLE IF NOT EXISTS producto (
                    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre VARCHAR(120) NOT NULL,
                    precio INT NOT NULL,
                    stock  INT NOT NULL
                )
                """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS pedido (
                    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cliente_nombre      VARCHAR(120),
                    cliente_email       VARCHAR(120) NOT NULL,
                    monto_total         INT,
                    modalidad_entrega   VARCHAR(20),
                    process_instance_id VARCHAR(64),
                    creado              TIMESTAMP,
                    desenlace           VARCHAR(30),
                    desenlace_motivo    VARCHAR(200),
                    desenlace_en        TIMESTAMP
                )
                """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS notificacion(
                    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    pedido_id      INT NOT NULL REFERENCES pedido(id),
                    tipo           VARCHAR(40) NOT NULL,
                    destinatario   VARCHAR(120) NOT NULL,
                    mensaje        VARCHAR(300),
                    registrada_en  TIMESTAMP
                )
                """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS pedido_item (
                    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    pedido_id   INT NOT NULL REFERENCES pedido(id),
                    producto_id INT NOT NULL REFERENCES producto(id),
                    precio      INT NOT NULL
                )
                """);
                

            int cuantos;
            try (ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM producto")) {
                rs.next();
                cuantos = rs.getInt(1);
            }

            if (cuantos == 0) {
                st.execute("INSERT INTO producto (nombre, precio, stock) VALUES ('Velador de madera con cajon', 48000, 1)");
                st.execute("INSERT INTO producto (nombre, precio, stock) VALUES ('Lote de 4 novelas chilenas', 6500, 1)");
                st.execute("INSERT INTO producto (nombre, precio, stock) VALUES ('Comoda de seis cajones', 89000, 1)");
                st.execute("INSERT INTO producto (nombre, precio, stock) VALUES ('Caja de 12 libros infantiles', 12000, 1)");
                System.out.println("Catalogo inicial cargado.");
            }
        }
    }

    public int insertar(Pedido p) throws SQLException {
        String sql = """
            INSERT INTO pedido
                (cliente_nombre, cliente_email, monto_total, modalidad_entrega,
                 process_instance_id, creado)
            VALUES (?, ?, ?, ?, ?, ?)
            """;

        conn.setAutoCommit(false);

        try (PreparedStatement st = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            st.setString(1, p.getClienteNombre());
            st.setString(2, p.getClienteEmail());
            st.setInt(3, p.getMontoTotal());
            st.setString(4, p.getModalidadEntrega());
            st.setString(5, p.getProcessInstanceId());
            st.setObject(6, p.getCreado());
            st.executeUpdate();

            int pedidoId;
            try (ResultSet rs = st.getGeneratedKeys()) {
                rs.next();
                pedidoId = rs.getInt(1);
            }

            if (p.getItems() != null) {
                for (PedidoItem item : p.getItems()) {
                    insertarItem(pedidoId, item.getProductoId(), item.getPrecio());
                }
            }

            conn.commit();
            return pedidoId;

        } catch (SQLException e) {
            conn.rollback();
            throw e;

        } finally {
            conn.setAutoCommit(true);
        }
    }

    public List<Pedido> listar() throws SQLException {
        List<Pedido> pedidos = new ArrayList<>();

        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM pedido ORDER BY id")) {

            while (rs.next()) {
                pedidos.add(mapear(rs));

            }
        }
        return pedidos;

    }

    public Pedido buscarPorId(int id) throws SQLException {

        try (PreparedStatement st = conn.prepareStatement("SELECT * FROM pedido WHERE id = ?")) {
            st.setInt(1, id);

            try (ResultSet rs = st.executeQuery()) {
                return rs.next() ? mapear(rs) : null;
                
            }
        }
    }

    public Producto buscarProducto(int id) throws SQLException {
        String sql = "SELECT * FROM producto WHERE id = ?";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, id);

            try (ResultSet rs = st.executeQuery()) {
                if (!rs.next()) {
                    return null;
                }
                Producto p = new Producto();
                p.setId(rs.getInt("id"));
                p.setNombre(rs.getString("nombre"));
                p.setPrecio(rs.getInt("precio"));
                p.setStock(rs.getInt("stock"));
                return p;
            }
        }
    }

    public boolean registrarDesenlace(int pedidoId, String valor, String motivo) throws SQLException {

        String sql = """
            UPDATE pedido
            SET desenlace = ?, desenlace_motivo = ?, desenlace_en = ?
            WHERE id = ?
            """;

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, valor);
            st.setString(2, motivo);
            st.setObject(3, LocalDateTime.now());
            st.setInt(4, pedidoId);
            return st.executeUpdate() == 1;
        }
    }

    public boolean insertarNotificacion(int pedidoId, String tipo, String destinatario, String mensaje) throws SQLException {
        String sql = """
            INSERT INTO notificacion
                (pedido_id, tipo, destinatario, mensaje, registrada_en)
            SELECT ?, ?, ?, ?, ?
            WHERE NOT EXISTS (
                SELECT 1 FROM notificacion
                WHERE pedido_id = ? AND tipo = ?
            )
            """;

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, pedidoId);
            st.setString(2, tipo);
            st.setString(3, destinatario);
            st.setString(4, mensaje);
            st.setObject(5, LocalDateTime.now());
            st.setInt(6, pedidoId);
            st.setString(7, tipo);
            return st.executeUpdate() == 1;

        }
    }

    public List<Producto> listarProductos() throws SQLException {
        List<Producto> productos = new ArrayList<>();

        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM producto ORDER BY id")) {
            
            while (rs.next()) {
                Producto p = new Producto();
                p.setId(rs.getInt("id"));
                p.setNombre(rs.getString("nombre"));
                p.setStock(rs.getInt("stock"));
                p.setPrecio(rs.getInt("precio"));
                productos.add(p);
            }    
        }
        return productos;
    }

    public void insertarItem(int pedidoId, int productoId, int precio) throws SQLException {
        String sql = """
            INSERT INTO pedido_item (pedido_id, producto_id, precio)
            VALUES (?, ?, ?)
            """;

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, pedidoId);
            st.setInt(2, productoId);
            st.setInt(3, precio);
            st.executeUpdate();
        }
    }

    public List<PedidoItem> listarItems(int pedidoId) throws SQLException {
        List<PedidoItem> items = new ArrayList<>();

        String sql = """
            SELECT i.producto_id, p.nombre, i.precio
            FROM pedido_item i
            JOIN producto p ON p.id = i.producto_id
            WHERE i.pedido_id = ?
            ORDER BY i.id
            """;

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, pedidoId);

            try (ResultSet rs = st.executeQuery()) {
                while (rs.next()) {
                    PedidoItem item = new PedidoItem();
                    item.setProductoId(rs.getInt("producto_id"));
                    item.setNombre(rs.getString("nombre"));
                    item.setPrecio(rs.getInt("precio"));
                    items.add(item);
                }
            }
        }
        return items;
    }

    public boolean reservarObjetos(List<PedidoItem> items) throws SQLException {
        String sql = "UPDATE producto SET stock = stock - 1 WHERE id = ? AND stock >= 1";

        conn.setAutoCommit(false);

        try (PreparedStatement st = conn.prepareStatement(sql)) {

            for (PedidoItem item : items) {
                st.setInt(1, item.getProductoId());

                if (st.executeUpdate() != 1) {
                    conn.rollback();
                    return false;
                }
            }

            conn.commit();
            return true;

        } catch (SQLException e) {
            conn.rollback();
            throw e;

        } finally {
            conn.setAutoCommit(true);
        }
    }


    public boolean asignarInstancia(int pedidoId, String processInstanceId) throws SQLException {

        String sql = "UPDATE pedido SET process_instance_id = ? WHERE id = ?";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, processInstanceId);
            st.setInt(2, pedidoId);
            return st.executeUpdate() == 1;
        }
    }



        private Pedido mapear(ResultSet rs) throws SQLException {
        Pedido p = new Pedido();
        p.setId(rs.getInt("id"));
        p.setClienteNombre(rs.getString("cliente_nombre"));
        p.setClienteEmail(rs.getString("cliente_email"));
        p.setMontoTotal(rs.getInt("monto_total"));
        p.setModalidadEntrega(rs.getString("modalidad_entrega"));
        p.setProcessInstanceId(rs.getString("process_instance_id"));
        p.setCreado(rs.getObject("creado", LocalDateTime.class));
        p.setDesenlace(rs.getString("desenlace"));
        p.setDesenlaceMotivo(rs.getString("desenlace_motivo"));
        p.setDesenlaceEn(rs.getObject("desenlace_en", LocalDateTime.class));
        return p;

    }
}
