package cl.mapuescuela.pedidos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PedidoDAO {

    private final Connection conn;

    public PedidoDAO(Connection conn) {
        this.conn = conn;
    }

    public void crearTablas() throws SQLException {
        try (Statement st = conn.createStatement()) {

            st.execute("""
                CREATE TABLE IF NOT EXISTS producto (
                    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre VARCHAR(120) NOT NULL,
                    stock  INT NOT NULL
                )
                """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS pedido (
                    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cliente_nombre      VARCHAR(120),
                    cliente_email       VARCHAR(120),
                    monto_total         INT,
                    modalidad_entrega   VARCHAR(20),
                    producto_id         INT,
                    cantidad            INT NOT NULL CHECK (cantidad > 0),
                    process_instance_id VARCHAR(64),
                    creado              TIMESTAMP
                )
                """);

            st.execute("INSERT INTO producto (nombre, stock) VALUES ('Sofa de dos cuerpos', 1)");
            st.execute("INSERT INTO producto (nombre, stock) VALUES ('Caja de libros infantiles', 5)");
        }
    }

    public int insertar(Pedido p) throws SQLException {
        String sql = """
            INSERT INTO pedido
                (cliente_nombre, cliente_email, monto_total, modalidad_entrega,
                 producto_id, cantidad, process_instance_id, creado)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """;

        try (PreparedStatement st = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            st.setString(1, p.getClienteNombre());
            st.setString(2, p.getClienteEmail());
            st.setInt(3, p.getMontoTotal());
            st.setString(4, p.getModalidadEntrega());
            st.setInt(5, p.getProductoId());
            st.setInt(6, p.getCantidad());
            st.setString(7, p.getProcessInstanceId());
            st.setObject(8, p.getCreado());
            st.executeUpdate();

            try (ResultSet rs = st.getGeneratedKeys()) {
                rs.next();
                return rs.getInt(1);
            }
        }
    }

    public List<Pedido> listar() throws SQLException {
        List<Pedido> pedidos = new ArrayList<>();

        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM pedido ORDER BY id")) {

            while (rs.next()) {
                pedidos.add(mapear(rs));

            }
        }
        return pedidos;

    }

    public Pedido buscarPorId(int id) throws SQLException {

        try (PreparedStatement st = conn.prepareStatement("SELECT * FROM pedido WHERE id = ?")) {
            st.setInt(1, id);

            try (ResultSet rs = st.executeQuery()) {
                return rs.next() ? mapear(rs) : null;
                
            }
        }
    }

    public boolean existeProducto(int productoId) throws SQLException {
        String sql = "SELECT 1 FROM producto WHERE id = ?";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, productoId);

            try (ResultSet rs = st.executeQuery()) {
                return rs.next();
            }
        }
    }

    public boolean descontarStock(int productoId, int cantidad) throws SQLException {
        String sql = "UPDATE producto SET stock = stock - ? WHERE id = ? AND stock >= ?";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, cantidad);
            st.setInt(2, productoId);
            st.setInt(3, cantidad);
            return st.executeUpdate() == 1;
        }
    }

        private Pedido mapear(ResultSet rs) throws SQLException {
        Pedido p = new Pedido();
        p.setId(rs.getInt("id"));
        p.setClienteNombre(rs.getString("cliente_nombre"));
        p.setClienteEmail(rs.getString("cliente_email"));
        p.setMontoTotal(rs.getInt("monto_total"));
        p.setModalidadEntrega(rs.getString("modalidad_entrega"));
        p.setProductoId(rs.getInt("producto_id"));
        p.setCantidad(rs.getInt("cantidad"));
        p.setProcessInstanceId(rs.getString("process_instance_id"));
        p.setCreado(rs.getObject("creado", LocalDateTime.class));
        return p;
    }
}