package cl.mapuescuela.pedidos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PedidoDAO {

    private final Connection conn;

    public PedidoDAO(Connection conn) {
        this.conn = conn;
    }

    public void crearTablas() throws SQLException {
        try (Statement st = conn.createStatement()) {

            st.execute("""
                CREATE TABLE IF NOT EXISTS producto (
                    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre VARCHAR(120) NOT NULL,
                    stock  INT NOT NULL
                )
                """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS pedido (
                    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cliente_nombre      VARCHAR(120),
                    cliente_email       VARCHAR(120) NOT NULL,
                    monto_total         INT,
                    modalidad_entrega   VARCHAR(20),
                    producto_id         INT REFERENCES producto(id),
                    cantidad            INT NOT NULL CHECK (cantidad > 0),
                    process_instance_id VARCHAR(64),
                    creado              TIMESTAMP,
                    desenlace           VARCHAR(30),
                    desenlace_motivo    VARCHAR(200),
                    desenlace_en        TIMESTAMP
                )
                """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS notificacion(
                    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    pedido_id      INT NOT NULL REFERENCES pedido(id),
                    tipo           VARCHAR(40) NOT NULL,
                    destinatario   VARCHAR(120) NOT NULL,
                    mensaje        VARCHAR(300),
                    registrada_en  TIMESTAMP
                )
                """);

            st.execute("INSERT INTO producto (nombre, stock) VALUES ('Sofa de dos cuerpos', 1)");
            st.execute("INSERT INTO producto (nombre, stock) VALUES ('Caja de libros infantiles', 5)");
        }
    }

    public int insertar(Pedido p) throws SQLException {
        String sql = """
            INSERT INTO pedido
                (cliente_nombre, cliente_email, monto_total, modalidad_entrega,
                 producto_id, cantidad, process_instance_id, creado)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """;

        try (PreparedStatement st = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            st.setString(1, p.getClienteNombre());
            st.setString(2, p.getClienteEmail());
            st.setInt(3, p.getMontoTotal());
            st.setString(4, p.getModalidadEntrega());
            st.setInt(5, p.getProductoId());
            st.setInt(6, p.getCantidad());
            st.setString(7, p.getProcessInstanceId());
            st.setObject(8, p.getCreado());
            st.executeUpdate();

            try (ResultSet rs = st.getGeneratedKeys()) {
                rs.next();
                return rs.getInt(1);
            }
        }
    }

    public List<Pedido> listar() throws SQLException {
        List<Pedido> pedidos = new ArrayList<>();

        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM pedido ORDER BY id")) {

            while (rs.next()) {
                pedidos.add(mapear(rs));

            }
        }
        return pedidos;

    }

    public Pedido buscarPorId(int id) throws SQLException {

        try (PreparedStatement st = conn.prepareStatement("SELECT * FROM pedido WHERE id = ?")) {
            st.setInt(1, id);

            try (ResultSet rs = st.executeQuery()) {
                return rs.next() ? mapear(rs) : null;
                
            }
        }
    }

    public boolean existeProducto(int productoId) throws SQLException {
        String sql = "SELECT 1 FROM producto WHERE id = ?";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, productoId);

            try (ResultSet rs = st.executeQuery()) {
                return rs.next();
            }
        }
    }

    public boolean descontarStock(int productoId, int cantidad) throws SQLException {
        String sql = "UPDATE producto SET stock = stock - ? WHERE id = ? AND stock >= ?";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, cantidad);
            st.setInt(2, productoId);
            st.setInt(3, cantidad);
            return st.executeUpdate() == 1;
        }
    }

    public boolean registrarDesenlace(int pedidoId, String valor, String motivo) throws SQLException {

        String sql = """
            UPDATE pedido
            SET desenlace = ?, desenlace_motivo = ?, desenlace_en = ?
            WHERE id = ?
            """;

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, valor);
            st.setString(2, motivo);
            st.setObject(3, LocalDateTime.now());
            st.setInt(4, pedidoId);
            return st.executeUpdate() == 1;
        }
    }

    public boolean insertarNotificacion(int pedidoId, String tipo, String destinatario, String mensaje) throws SQLException {
        String sql = """
            INSERT INTO notificacion
                (pedido_id, tipo, destinatario, mensaje, registrada_en)
            SELECT ?, ?, ?, ?, ?
            WHERE NOT EXISTS (
                SELECT 1 FROM notificacion
                WHERE pedido_id = ? AND tipo = ?
            )
            """;

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setInt(1, pedidoId);
            st.setString(2, tipo);
            st.setString(3, destinatario);
            st.setString(4, mensaje);
            st.setObject(5, LocalDateTime.now());
            st.setInt(6, pedidoId);
            st.setString(7, tipo);
            return st.executeUpdate() == 1;

        }
    }

    public List<Producto> listarProductos() throws SQLException {
        List<Producto> productos = new ArrayList<>();

        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM producto ORDER BY id")) {
            
            while (rs.next()) {
                Producto p = new Producto();
                p.setId(rs.getInt("id"));
                p.setNombre(rs.getString("nombre"));
                p.setStock(rs.getInt("stock"));
                productos.add(p);
            }    
        }
        return productos;
    }

    public boolean asignarInstancia(int pedidoId, String processInstanceId) throws SQLException {

        String sql = "UPDATE pedido SET process_instance_id = ? WHERE id = ?";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, processInstanceId);
            st.setInt(2, pedidoId);
            return st.executeUpdate() == 1;
        }
    }



        private Pedido mapear(ResultSet rs) throws SQLException {
        Pedido p = new Pedido();
        p.setId(rs.getInt("id"));
        p.setClienteNombre(rs.getString("cliente_nombre"));
        p.setClienteEmail(rs.getString("cliente_email"));
        p.setMontoTotal(rs.getInt("monto_total"));
        p.setModalidadEntrega(rs.getString("modalidad_entrega"));
        p.setProductoId(rs.getInt("producto_id"));
        p.setCantidad(rs.getInt("cantidad"));
        p.setProcessInstanceId(rs.getString("process_instance_id"));
        p.setCreado(rs.getObject("creado", LocalDateTime.class));
        p.setDesenlace(rs.getString("desenlace"));
        p.setDesenlaceMotivo(rs.getString("desenlace_motivo"));
        p.setDesenlaceEn(rs.getObject("desenlace_en", LocalDateTime.class));
        return p;

    }
}
